exclude_paths:
  - vendor
detectors:
  # You can disable smells completely
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    exclude:
      - 'Admins::DepartmentsController#department_users_params'
      - 'User#is?'
      - 'Populators::DepartmentUserPopulate'
      - 'AdminDashboard#self.audience_members'
      - 'Users::DocumentRecipientsController'
      - 'Admins::AudienceMembersController#process_csv'
      - 'Admins::DepartmentsController#users_params'
  Attribute:
    exclude:
      - 'Administrator'
  FeatureEnvy:
    exclude:
      - 'Admins::UsersController#remove_empty_password'
      - 'User#populate_modules'
      - 'CreateAudienceMembersFromCsv#included?'
      - 'Users::DocumentsController#users_params'
      - 'Admins::DepartmentModulesController#users_params'
      - 'Logics::Document::Recipient#add'
  UtilityFunction:
    exclude:
      - 'Admins::AdministratorsController#resource_name'
      - 'CreateAudienceMembersFromCsv#registered?'

  TooManyInstanceVariables:
    exclude:
      - 'CreateAudienceMembersFromCsv'

  TooManyStatements:
    exclude:
      - 'Members::BuilderMethods#build'
      - 'CreateAudienceMembersFromCsv'
      - 'Populators::DepartmentUserPopulate#create'

  NilCheck:
    exclude:
      - 'Users::TeamDepartmentsModulesController#set_department'
      - 'Users::TeamDepartmentsModulesController#set_module'
      - 'Logics::Document::Recipient#add'

  InstanceVariableAssumption:
    exclude:
      - 'JsonValidator'

  NestedIterators:
    exclude:
      - 'Populators::DepartmentUserPopulate'

directories:
  "app/controllers":
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    TooManyInstanceVariables:
      max_instance_variables: 6
    TooManyStatements:
      max_statements: 10
    TooManyMethods:
      max_methods: 20
  "app/helpers":
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
  "app/inputs":
    InstanceVariableAssumption:
      enabled: false
  "app/uploaders":
    UtilityFunction:
      enabled: false
  "lib/populators":
    UtilityFunction:
      enabled: false
