database: &database
  db.username: postgres
  db.password: postgres
  db.host: db

mailer: &mailer
  mailer.host: localhost
  mailer.port: "3000"
  mailer.from: "sgcd@utfpr.edu.br"

app: &app
  app.host: "localhost:3000"

development:
  <<: *database
  <<: *mailer
  <<: *app

test:
  <<: *database
  <<: *mailer
  <<: *app
